server:
  port: 9001


spring:
  application:
    name: comment-service
  cloud:
    config:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://comment-db:3306/db_comment
    username: springuser
    password: ThePassword
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}


#defaultZone: http://localhost:8761/eureka/
#url: jdbc:mysql://${MYSQL_HOST:localhost}/db_user