server:
  port: 9001


spring:
  application:
    name: COMMENT-SERVICE
  cloud:
    config:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://comment-db:3306/db_comment
    username: springuser
    password: ThePassword
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    register-with-eureka : true
    fetch-registry : true
    service-url :
      defaultZone: http://service-registry:8761/eureka/
  instance:
    hostname: localhost