apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-app-deployment
  labels:
    app: article-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: article-app
  template:
    metadata:
      labels:
        app: article-app
    spec:
      containers:
        - name: article-app
          image: article-service:0.0.1-SNAPSHOT
          ports:
            - containerPort: 9003
---
apiVersion: v1
kind: Service
metadata:
  name: article-app-service
spec:
  selector:
    app: article-app
  ports:
    - protocol: TCP
      port: 9003
      targetPort: 9003