server:
  port: 9191

spring:
  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}


#defaultZone: http://localhost:8761/eureka/