server:
    port: 9191

spring:
  main:
    web-application-type: reactive
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path = /user/**
        - id: COMMENT-SERVICE
          uri: lb://COMMENT-SERVICE
          predicates:
            -Path= /comment/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

#
#eureka:
#  client:
#    register-with-eureka : false
#    fetch-registry: false