server:
  port: 9191

spring:
  application:
    name: API-GATEWAY

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    hostname: localhost

#defaultZone: http://localhost:8761/eureka/