server:
  port: 9003

spring:
  application:
    name: article-service
  cloud:
    config:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://article-db:3306/db_article
    username: springuser
    password: ThePassword
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}


#      defaultZone: http://localhost:8761/eureka/
#url: jdbc:mysql://${MYSQL_HOST:localhost}/db_user