server:
  port: 9002

spring:
  application:
    name: USER-SERVICE
  cloud:
    config:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://user-db:3306/db_user
    username: springuser
    password: ThePassword
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    hostname: localhost


#url: jdbc:mysql://${MYSQL_HOST:localhost}/db_user
#defaultZone: http://localhost:8761/eureka/
